[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.14.0"
seq-macro = "0.3.5"
union-find = "0.4.3"
